/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "apple-hello-effect-demo": {
    name: "apple-hello-effect-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/apple-hello-effect.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () => import("@/registry/examples/apple-hello-effect.tsx")
    ),
  },
};
